// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext {
        def vcode = (int)(((new Date().getTime()/1000) - 1559347200) / 10)
        appVersionCode = vcode
        appVersionName = '26.08.21'
        orientation = "unspecified"
        provider_authority = "tech.ula.provider.fileprovider"
        support_assets_version = "v1.4.18"
        kotlin_version = '1.9.20'
        android_plugin = '8.7.2'
        jacoco_version = '0.8.4'
        navigation_version = '2.5.0'
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$android_plugin"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$navigation_version"
        classpath "org.jacoco:org.jacoco.core:$jacoco_version"
        classpath 'de.undercouch:gradle-download-task:5.6.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
