rootProject.name = "UserLAnd"
include ':app', ':UserLAndLibrary'
project(':UserLAndLibrary').projectDir = new File('UserLAndLibrary/app')

include ':pubkeyGenerator', ':bVNC', ':remoteClientLib'
project(':bVNC').projectDir = new File('UserLAndLibrary/remote-desktop-clients/bVNC')
project(':pubkeyGenerator').projectDir = new File('UserLAndLibrary/remote-desktop-clients/pubkeyGenerator')
project(':remoteClientLib').projectDir = new File('UserLAndLibrary/remote-desktop-clients/remoteClientLib')

include ':remoteClientLib:jni:libs:deps:FreeRDP:client:Android:Studio:freeRDPCore'
project(':remoteClientLib:jni:libs:deps:FreeRDP:client:Android:Studio:freeRDPCore').projectDir = new File('UserLAndLibrary/remote-desktop-clients/remoteClientLib/jni/libs/deps/FreeRDP/client/Android/Studio/freeRDPCore/')

include ':CustomLibrary'
project(':CustomLibrary').projectDir = new File('CustomLibrary')

// Replacement for the termux-app terminal; see UserLAndLibrary/terminal.
include ':terminal'
project(':terminal').projectDir = new File('UserLAndLibrary/terminal')

include ':adbndk'
project(':adbndk').projectDir = new File('../../adb-ndk/android')