# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

update_fastlane

default_platform(:android)

platform :android do

  desc "Update changelogs based on latest version code"
  lane :update_changelogs do
    version_code = File.read("../app/versionCode.txt")

    changelog = changelog_from_git_commits(merge_commit_filtering: "exclude_merges", pretty: "- %s")

    changelogs_dir = "metadata/android/en-US/changelogs"
    changelog_file = changelogs_dir + "/" + version_code + ".txt"

    sh("mkdir", "-p", changelogs_dir)
    File.open(changelog_file, 'w') do |file|
      file.write changelog
    end
  end

  desc "Release to Github"
  lane :github_release do
    gradle(task: "reportVersionCode")
    version_code = File.read("../app/versionCode.txt")
    changelogs_dir = "metadata/android/en-US/changelogs"
    changelog_file = changelogs_dir + "/" + version_code + ".txt"

    gradle(task: "reportVersionName")
    version_name = File.read("../app/versionName.txt")
    release_name = "v" + version_name

    set_github_release(
      repository_name: "CypherpunkArmory/UserLAnd",
      api_token: ENV["GITHUB_RELEASE_TOKEN"],
      name: release_name,
      tag_name: release_name,
      description: (File.read(changelog_file) rescue "No changelog provided"),
      commitish: "releases",
      upload_assets: ["app/build/outputs/apk/release/app-release.apk"]
    )
  end

  desc "Deploy a new version to Google Play beta track"
  lane :deploy_beta do
    update_changelogs
    supply(apk: "app/build/outputs/apk/beta/app-beta.apk", track: "beta")
  end

  desc "Deploy a new version to the Google Play production track and Github releases"
  lane :deploy_production do
    update_changelogs
    github_release
    supply(apk: "app/build/outputs/apk/release/app-release.apk")
  end
end
